/**
 * Maps legacy Material Icons / Symbols names → Flaticon Uicons (regular-rounded).
 * Source: https://www.flaticon.com/uicons/interface-icons
 */
export const MATERIAL_TO_UICON: Record<string, string> = {
  account_tree: 'sitemap',
  add: 'plus',
  add_circle: 'plus',
  admin_panel_settings: 'admin-alt',
  alarm: 'alarm-clock',
  arrow_back: 'arrow-left',
  assessment: 'chart-histogram',
  assignment: 'clipboard-list',
  assignment_ind: 'clipboard-user',
  attach_file: 'clip',
  auto_awesome: 'sparkles',
  backspace: 'delete',
  badge: 'id-badge',
  bar_chart: 'chart-histogram',
  calendar_month: 'calendar',
  calendar_today: 'calendar-day',
  calendar_view_day: 'calendar-lines',
  calendar_view_week: 'calendar-week',
  call: 'phone-call',
  cancel: 'circle-xmark',
  category: 'apps',
  check: 'check',
  check_box: 'checkbox',
  check_circle: 'check-circle',
  chevron_left: 'angle-left',
  chevron_right: 'angle-right',
  class: 'chalkboard',
  close: 'cross',
  comment: 'comment',
  construction: 'tools',
  contact_phone: 'phone-call',
  content_copy: 'copy',
  dashboard: 'dashboard',
  date_range: 'calendar',
  delete: 'trash',
  delete_forever: 'trash-xmark',
  delete_sweep: 'trash',
  description: 'document',
  domain: 'building',
  done_all: 'check-double',
  edit: 'pencil',
  edit_note: 'edit',
  engineering: 'user-gear',
  error: 'circle-xmark',
  error_outline: 'exclamation',
  event: 'calendar',
  event_available: 'calendar-check',
  event_note: 'calendar-lines',
  event_seat: 'chair',
  expand_more: 'angle-down',
  fact_check: 'clipboard-check',
  filter_alt: 'filter',
  fingerprint: 'fingerprint',
  flag: 'flag',
  folder_open: 'folder-open',
  gavel: 'gavel',
  grade: 'star',
  grading: 'clipboard-list',
  groups: 'users',
  help_outline: 'interrogation',
  hourglass_top: 'hourglass-start',
  how_to_reg: 'user-check',
  hub: 'network',
  inbox: 'inbox',
  info: 'info',
  insert_drive_file: 'file',
  key: 'key',
  keyboard_double_arrow_left: 'angle-double-left',
  keyboard_double_arrow_right: 'angle-double-right',
  language: 'globe',
  lightbulb: 'bulb',
  link: 'link',
  list_alt: 'list',
  location_on: 'marker',
  lock: 'lock',
  login: 'sign-in-alt',
  logout: 'sign-out-alt',
  mail: 'envelope',
  manage_accounts: 'users-gear',
  meeting_room: 'meeting',
  menu: 'menu-burger',
  menu_book: 'book-open-cover',
  more_vert: 'menu-dots-vertical',
  note_alt: 'note',
  notes: 'notes',
  notifications: 'bell',
  notifications_active: 'bell-ring',
  open_in_new: 'share',
  palette: 'palette',
  pending_actions: 'pending',
  people: 'people',
  percent: 'percentage',
  person: 'user',
  person_add: 'user-add',
  person_off: 'user-slash',
  phone: 'phone-call',
  picture_as_pdf: 'file-pdf',
  priority_high: 'exclamation',
  public: 'globe',
  radio_button_unchecked: 'circle',
  refresh: 'refresh',
  remove_done: 'square-minus',
  restart_alt: 'rotate-right',
  rule: 'scale',
  save: 'disk',
  schedule: 'clock',
  school: 'graduation-cap',
  search: 'search',
  security: 'shield-check',
  send: 'paper-plane',
  settings: 'settings',
  shield: 'shield',
  star: 'star',
  sticky_note_2: 'note-sticky',
  summarize: 'document',
  supervisor_account: 'user-gear',
  swap_horiz: 'exchange',
  table_chart: 'table',
  table_view: 'table-layout',
  task: 'list-check',
  task_alt: 'checkbox',
  thumb_up: 'thumbs-up-trust',
  timer: 'time-forward',
  title: 'text',
  today: 'calendar-day',
  trending_up: 'chart-line-up',
  tune: 'settings-sliders',
  update: 'time-forward',
  upload: 'upload',
  upload_file: 'file',
  verified: 'badge-check',
  view_agenda: 'list',
  view_column: 'columns-3',
  view_kanban: 'chart-kanban',
  visibility: 'eye',
  visibility_off: 'eye-crossed',
  warning: 'triangle-warning',
  weekend: 'calendar-week',
  home: 'home',
  expand_less: 'angle-up',
  keyboard_arrow_down: 'angle-down',
  keyboard_arrow_up: 'angle-up',
  analytics: 'chart-mixed',
  folder: 'folder',
};

/** Resolve any icon token (Material name or raw uicon slug) to a Flaticon class slug. */
export function resolveUiconSlug(name: string | null | undefined): string {
  const raw = (name ?? '').trim();
  if (!raw) return 'apps';
  if (raw.startsWith('fi-rr-') || raw.startsWith('fi-sr-')) {
    return raw.replace(/^fi-(rr|sr)-/, '');
  }
  if (MATERIAL_TO_UICON[raw]) return MATERIAL_TO_UICON[raw];
  // already a uicon slug like "graduation-cap"
  if (/^[a-z0-9-]+$/.test(raw)) return raw;
  return 'apps';
}

export function uiconClass(name: string | null | undefined, solid = false): string {
  const slug = resolveUiconSlug(name);
  return solid ? `fi fi-sr-${slug}` : `fi fi-rr-${slug}`;
}
